# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-20 08:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='tytuł')),
                ('cover', models.ImageField(upload_to='covers/', verbose_name='okładka')),
                ('translator', models.CharField(max_length=100, verbose_name='tłumaczenie')),
                ('original', models.TextField(help_text='(i podstawa przekładu)', verbose_name='tytuł orginału')),
                ('edition', models.CharField(max_length=50, verbose_name='wydanie')),
                ('isbn', models.CharField(blank=True, max_length=18, verbose_name='ISBN')),
                ('circulation', models.CharField(blank=True, max_length=50, verbose_name='nakład')),
                ('price', models.IntegerField(blank=True, null=True, verbose_name='cena minimalna')),
                ('store_id', models.IntegerField(blank=True, help_text='product_id z adresu produktu na bractwotrojka.pl', null=True, verbose_name='ID w sklepie')),
                ('embed', models.TextField(blank=True, help_text='wygenerowany na flipstack.com', null=True, verbose_name='Kod embed książki')),
                ('hidden', models.BooleanField(default=False, verbose_name='ukryj na stronie')),
            ],
        ),
    ]
