# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-20 11:43
from __future__ import unicode_literals

import apps.books.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ('-id',), 'verbose_name': 'książka', 'verbose_name_plural': 'książki'},
        ),
        migrations.AlterField(
            model_name='book',
            name='embed',
            field=models.TextField(blank=True, help_text='wygenerowany na flipstack.com', null=True, validators=[apps.books.models.validate_has_src], verbose_name='Kod embed książki'),
        ),
        migrations.AlterField(
            model_name='book',
            name='translator',
            field=models.CharField(max_length=100, verbose_name='tłumaczka'),
        ),
    ]
