# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-20 12:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_auto_20170820_1343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='price',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='cena minimalna'),
        ),
        migrations.AlterField(
            model_name='book',
            name='store_id',
            field=models.PositiveIntegerField(blank=True, help_text='product_id z adresu produktu na bractwotrojka.pl', null=True, verbose_name='ID w sklepie'),
        ),
    ]
