# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-20 12:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_auto_20170820_1413'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ('-order', '-id'), 'verbose_name': 'książka', 'verbose_name_plural': 'książki'},
        ),
        migrations.AddField(
            model_name='book',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
