# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-20 13:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_auto_20170820_1450'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='author',
            field=models.CharField(default='Nieznany', max_length=100, verbose_name='autor'),
            preserve_default=False,
        ),
    ]
