# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-21 18:52
from __future__ import unicode_literals

import apps.books.models
from django.db import migrations, models
from django.utils.text import slugify


def migrate_data_forward(apps, schema_editor):
    Book = apps.get_model("books", "Book")
    for book in Book.objects.all():
        book.slug = slugify(book.title)
        book.save()


def migrate_data_backward(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_book_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='slug',
            field=models.SlugField(blank=True, help_text='wykorzystywane w adresie strony', max_length=100, verbose_name='identyfikator'),
        ),
        migrations.AlterField(
            model_name='book',
            name='cover',
            field=models.ImageField(upload_to=apps.books.models.PathAndRemoveUnicode('covers/'), verbose_name='okładka'),
        ),
        migrations.RunPython(
            migrate_data_forward,
            migrate_data_backward,
        ),
    ]
