# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-21 19:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0008_auto_20170821_2100'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='description',
            field=models.TextField(default='', help_text="możesz używać znaczników formatowania <a href='http://commonmark.org/help/'>MarkDown</a>", verbose_name='Opis'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='book',
            name='original',
            field=models.TextField(blank=True, help_text="możesz używać znaczników formatowania <a href='http://commonmark.org/help/'>MarkDown</a>", verbose_name='tytuł orginału'),
        ),
    ]
