# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-05-05 17:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0010_auto_20180505_1923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='base',
            field=models.TextField(blank=True, help_text="możesz używać znaczników formatowania <a href='http://commonmark.org/help/'>MarkDown</a>", verbose_name='podstawa wydania'),
        ),
    ]
