# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-20 11:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='nazwa')),
                ('slug', models.CharField(help_text='wykorzystywane w adresie strony', max_length=100, verbose_name='identyfikator')),
                ('text', models.TextField(help_text='(i podstawa przekładu)', verbose_name='Treść')),
                ('menu', models.BooleanField(default=False, verbose_name='pokaż w menu')),
            ],
            options={
                'verbose_name': 'strona',
                'verbose_name_plural': 'strony',
            },
        ),
    ]
