# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-20 12:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='menu',
            field=models.BooleanField(default=True, verbose_name='pokaż w menu'),
        ),
        migrations.AlterField(
            model_name='page',
            name='slug',
            field=models.CharField(help_text='wykorzystywane w adresie strony', max_length=100, unique=True, verbose_name='identyfikator'),
        ),
        migrations.AlterField(
            model_name='page',
            name='text',
            field=models.TextField(help_text="możesz używać znaczników formatowania <a href='http://commonmark.org/help/'>MarkDown</a>", verbose_name='Treść'),
        ),
    ]
