# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-20 12:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_auto_20170820_1413'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='page',
            options={'ordering': ('-order', '-id'), 'verbose_name': 'strona', 'verbose_name_plural': 'strony'},
        ),
    ]
