# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-20 12:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_auto_20170820_1418'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='page',
            options={'ordering': ('order', 'id'), 'verbose_name': 'strona', 'verbose_name_plural': 'strony'},
        ),
        migrations.AlterField(
            model_name='page',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='kolejność'),
        ),
    ]
